import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = dirname(fileURLToPath(import.meta.url))
const inputFile = join(root, "limits.json")
const knownFields = [
  "version",
  "inputFileBytes",
  "packBytes",
  "overrideBytes",
  "jsonBytes",
  "canvasDimension",
  "canvasPixels",
  "psdLayers",
  "channelDecodedBytes",
  "decodedBytes",
  "catalogDecodedBytes",
  "outputBytes",
  "imageAllocationBytes",
  "outputLayers",
  "meshVertices",
  "totalMeshVertices",
  "strandWeightEntries",
  "drawableDimension",
  "drawablePixels",
  "decodeSeconds",
]

export async function writeRigLimits(outputFile) {
  const source = JSON.parse(await readFile(inputFile, "utf8"))
  if (source === null || typeof source !== "object" || Array.isArray(source)) {
    throw new Error("limits.json must contain an object")
  }
  const actualFields = Object.keys(source)
  if (actualFields.length !== knownFields.length || actualFields.some((field, index) => field !== knownFields[index])) {
    throw new Error(`limits.json fields must exactly match ${knownFields.join(", ")}`)
  }
  for (const field of knownFields) {
    const value = source[field]
    if (!Number.isSafeInteger(value) || value <= 0) {
      throw new Error(`limits.json ${field} must be a positive safe integer`)
    }
  }
  if (source.version !== 1) throw new Error("limits.json version must be 1")

  const lines = [
    "// Generated by native/rig/build-limits.mjs; do not edit.",
    "enum RigLimits {",
    ...knownFields.map(field => `    static let ${field} = ${source[field]}`),
    "}",
    "",
  ]
  await mkdir(dirname(outputFile), { recursive: true })
  await writeFile(outputFile, lines.join("\n"), "utf8")
}
